local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, opts)
vim.keymap.set('n', '<leader>fg', builtin.live_grep, opts)
vim.keymap.set('n', '<leader>fb', builtin.buffers, opts)
vim.keymap.set('n', '<leader>fgb', builtin.git_branches, opts)
vim.keymap.set('n', '<leader>fgc', builtin.git_commits, opts)
vim.keymap.set('n', '<leader>fgf', builtin.git_files, opts)
-- Resent commands. <C-e> to insert into the terminal.
vim.keymap.set('n', '<leader>frc', builtin.command_history, opts)
vim.keymap.set('n', '<leader>fr', builtin.resume, opts)
